import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "@/components";
import { Toaster } from "@/components/ui";
import { Recursive } from "next/font/google";

const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="hydrated antialiased">
      <Providers>
        <body className={recursive.className}>
          {children}
          <Toaster />
        </body>
      </Providers>
    </html>
  );
}
